
import { BossSpawnRaw, CraftingData } from './types';

// 1. DADOS DOS BOSSES
export const BOSS_DATA: BossSpawnRaw[] = [
  {"W":1,"layer":"Bicheon","time":"02:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"04:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"06:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"08:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"10:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"12:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"14:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"16:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"18:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"20:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"22:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"00:00","location":"Floresta do Touro Malvado","bosses":["Mata"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"01:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"03:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"05:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"07:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"09:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"11:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"13:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"15:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"17:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"19:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"21:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"23:00","location":"1F do Templo do Touro Demoniaco","bosses":["Touro Trovejante"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"03:00","location":"Santuario do Rei dos Touros","bosses":["Rei dos Touros Malvados"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"06:00","location":"Santuario do Rei dos Touros","bosses":["Rei dos Touros Malvados"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"09:00","location":"Santuario do Rei dos Touros","bosses":["Rei dos Touros Malvados"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"12:00","location":"Santuario do Rei dos Touros","bosses":["Rei dos Touros Malvados"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"15:00","location":"Santuario do Rei dos Touros","bosses":["Rei dos Touros Malvados"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"18:00","location":"Santuario do Rei dos Touros","bosses":["Rei dos Touros Malvados"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"21:00","location":"Santuario do Rei dos Touros","bosses":["Rei dos Touros Malvados"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"00:00","location":"Santuario do Rei dos Touros","bosses":["Rei dos Touros Malvados"],"tier":3},
  {"W":8,"layer":"Terra do Touro Branco","time":"01:00","location":"Circulo de Selo dos Gigantes Brancos","bosses":["Ye Wihuang (Velho)"],"tier":3},
  {"W":8,"layer":"Terra do Touro Branco","time":"05:00","location":"Circulo de Selo dos Gigantes Brancos","bosses":["Ye Wihuang (Velho)"],"tier":3},
  {"W":8,"layer":"Terra do Touro Branco","time":"09:00","location":"Circulo de Selo dos Gigantes Brancos","bosses":["Ye Wihuang (Velho)"],"tier":3},
  {"W":8,"layer":"Terra do Touro Branco","time":"13:00","location":"Circulo de Selo dos Gigantes Brancos","bosses":["Ye Wihuang (Velho)"],"tier":3},
  {"W":8,"layer":"Terra do Touro Branco","time":"17:00","location":"Circulo de Selo dos Gigantes Brancos","bosses":["Ye Wihuang (Velho)"],"tier":3},
  {"W":8,"layer":"Terra do Touro Branco","time":"21:00","location":"Circulo de Selo dos Gigantes Brancos","bosses":["Ye Wihuang (Velho)"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"01:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"03:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"05:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"07:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"09:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"11:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"13:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"15:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"17:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"19:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"21:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"23:00","location":"Jardim de Taehyul","bosses":["Taehyul"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"01:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"03:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"05:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"07:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"09:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"11:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"13:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"15:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"17:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"19:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"21:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"23:30","location":"Planicie das Viboras Mostruosas","bosses":["Imperador Tatu Sobrio"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"02:00","location":"Construção Principal do Culto Demôniaco","bosses":["Yiun"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"05:00","location":"Construção Principal do Culto Demôniaco","bosses":["Yiun"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"08:00","location":"Construção Principal do Culto Demôniaco","bosses":["Yiun"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"11:00","location":"Construção Principal do Culto Demôniaco","bosses":["Yiun"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"14:00","location":"Construção Principal do Culto Demôniaco","bosses":["Yiun"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"17:00","location":"Construção Principal do Culto Demôniaco","bosses":["Yiun"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"20:00","location":"Construção Principal do Culto Demôniaco","bosses":["Yiun"],"tier":3},
  {"W":7,"layer":"Navio da Miragem","time":"23:00","location":"Construção Principal do Culto Demôniaco","bosses":["Yiun"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"02:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"04:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"06:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"08:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"10:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"12:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"14:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"16:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"18:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"20:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"22:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"00:00","location":"Deserto da Fantasia","bosses":["Santidade Inabalável Nerfariox"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"03:00","location":"Circulo de Selo Suzerano","bosses":["Kurilaika"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"06:00","location":"Circulo de Selo Suzerano","bosses":["Kurilaika"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"09:00","location":"Circulo de Selo Suzerano","bosses":["Kurilaika"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"12:00","location":"Circulo de Selo Suzerano","bosses":["Kurilaika"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"15:00","location":"Circulo de Selo Suzerano","bosses":["Kurilaika"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"18:00","location":"Circulo de Selo Suzerano","bosses":["Kurilaika"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"21:00","location":"Circulo de Selo Suzerano","bosses":["Kurilaika"],"tier":3},
  {"W":4,"layer":"Phantasia","time":"00:00","location":"Circulo de Selo Suzerano","bosses":["Kurilaika"],"tier":3},
  {"W":2,"layer":"Vale da Serpente","time":"02:30","location":"Montanha da Lunula de Sangue","bosses":["Juhui"],"tier":3},
  {"W":2,"layer":"Vale da Serpente","time":"05:30","location":"Montanha da Lunula de Sangue","bosses":["Juhui"],"tier":3},
  {"W":2,"layer":"Vale da Serpente","time":"08:30","location":"Montanha da Lunula de Sangue","bosses":["Juhui"],"tier":3},
  {"W":2,"layer":"Vale da Serpente","time":"11:30","location":"Montanha da Lunula de Sangue","bosses":["Juhui"],"tier":3},
  {"W":2,"layer":"Vale da Serpente","time":"14:30","location":"Montanha da Lunula de Sangue","bosses":["Juhui"],"tier":3},
  {"W":2,"layer":"Vale da Serpente","time":"17:30","location":"Montanha da Lunula de Sangue","bosses":["Juhui"],"tier":3},
  {"W":2,"layer":"Vale da Serpente","time":"20:30","location":"Montanha da Lunula de Sangue","bosses":["Juhui"],"tier":3},
  {"W":2,"layer":"Vale da Serpente","time":"23:30","location":"Montanha da Lunula de Sangue","bosses":["Juhui"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"03:30","location":"Grande Muralha de Sabuk","bosses":["Faluk"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"06:30","location":"Grande Muralha de Sabuk","bosses":["Faluk"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"09:30","location":"Grande Muralha de Sabuk","bosses":["Faluk"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"12:30","location":"Grande Muralha de Sabuk","bosses":["Faluk"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"15:30","location":"Grande Muralha de Sabuk","bosses":["Faluk"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"18:30","location":"Grande Muralha de Sabuk","bosses":["Faluk"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"21:30","location":"Grande Muralha de Sabuk","bosses":["Faluk"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"00:30","location":"Grande Muralha de Sabuk","bosses":["Faluk"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"01:30","location":"Templo Ilusório","bosses":["Assombração Destruidora de História"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"04:30","location":"Templo Ilusório","bosses":["Assombração Destruidora de História"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"07:30","location":"Templo Ilusório","bosses":["Assombração Destruidora de História"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"10:30","location":"Templo Ilusório","bosses":["Assombração Destruidora de História"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"13:30","location":"Templo Ilusório","bosses":["Assombração Destruidora de História"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"16:30","location":"Templo Ilusório","bosses":["Assombração Destruidora de História"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"19:30","location":"Templo Ilusório","bosses":["Assombração Destruidora de História"],"tier":3},
  {"W":5,"layer":"Sabuk","time":"22:30","location":"Templo Ilusório","bosses":["Assombração Destruidora de História"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"02:30","location":"Necrópole de Nerfariox","bosses":["Gyo"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"08:30","location":"Necrópole de Nerfariox","bosses":["Gyo"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"14:30","location":"Necrópole de Nerfariox","bosses":["Gyo"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"20:30","location":"Necrópole de Nerfariox","bosses":["Gyo"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"03:30","location":"Tumulo de Rockcut","bosses":["Budu"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"09:30","location":"Tumulo de Rockcut","bosses":["Budu"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"15:30","location":"Tumulo de Rockcut","bosses":["Budu"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"21:30","location":"Tumulo de Rockcut","bosses":["Budu"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"02:30","location":"Tumulo de Rockcut","bosses":["Mara"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"05:30","location":"Tumulo de Rockcut","bosses":["Mara"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"08:30","location":"Tumulo de Rockcut","bosses":["Mara"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"11:30","location":"Tumulo de Rockcut","bosses":["Mara"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"14:30","location":"Tumulo de Rockcut","bosses":["Mara"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"17:30","location":"Tumulo de Rockcut","bosses":["Mara"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"20:30","location":"Tumulo de Rockcut","bosses":["Mara"],"tier":3},
  {"W":3,"layer":"Centro Espiritual","time":"23:30","location":"Tumulo de Rockcut","bosses":["Mara"],"tier":3},
  {"W":6,"layer":"Domínio","time":"04:30","location":"Cidade Bicheon","bosses":["Asura"],"tier":3},
  {"W":6,"layer":"Domínio","time":"10:30","location":"Cidade Bicheon","bosses":["Asura"],"tier":3},
  {"W":6,"layer":"Domínio","time":"16:30","location":"Cidade Bicheon","bosses":["Asura"],"tier":3},
  {"W":6,"layer":"Domínio","time":"22:30","location":"Cidade Bicheon","bosses":["Asura"],"tier":3},
  {"W":6,"layer":"Domínio","time":"02:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"04:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"06:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"08:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"10:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"12:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"14:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"16:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"18:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"20:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"22:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"00:30","location":"Cidade Bicheon","bosses":["Cheol Mokgang"],"tier":3},
  {"W":6,"layer":"Domínio","time":"05:30","location":"Bosque Fantasma","bosses":["Wuihan"],"tier":3},
  {"W":6,"layer":"Domínio","time":"11:30","location":"Bosque Fantasma","bosses":["Wuihan"],"tier":3},
  {"W":6,"layer":"Domínio","time":"17:30","location":"Bosque Fantasma","bosses":["Wuihan"],"tier":3},
  {"W":6,"layer":"Domínio","time":"23:30","location":"Bosque Fantasma","bosses":["Wuihan"],"tier":3},
  {"W":6,"layer":"Domínio","time":"06:30","location":"Labirinto Bicheon","bosses":["Yeticlops"],"tier":3},
  {"W":6,"layer":"Domínio","time":"12:30","location":"Labirinto Bicheon","bosses":["Yeticlops"],"tier":3},
  {"W":6,"layer":"Domínio","time":"18:30","location":"Labirinto Bicheon","bosses":["Yeticlops"],"tier":3},
  {"W":6,"layer":"Domínio","time":"00:30","location":"Labirinto Bicheon","bosses":["Yeticlops"],"tier":3},
  {"W":6,"layer":"Domínio","time":"01:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"03:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"05:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"07:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"09:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"11:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"13:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"15:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"17:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"19:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"21:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":6,"layer":"Domínio","time":"23:30","location":"Abismo da Mina Abandonada","bosses":["Hong Yeom Transformada"],"tier":3},
  {"W":1,"layer":"Bicheon","time":"02:30","location":"Cidade Unseo","bosses":["Jihwa"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"05:30","location":"Cidade Unseo","bosses":["Jihwa"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"08:30","location":"Cidade Unseo","bosses":["Jihwa"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"11:30","location":"Cidade Unseo","bosses":["Jihwa"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"14:30","location":"Cidade Unseo","bosses":["Jihwa"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"17:30","location":"Cidade Unseo","bosses":["Jihwa"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"20:30","location":"Cidade Unseo","bosses":["Jihwa"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"23:30","location":"Cidade Unseo","bosses":["Jihwa"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"03:30","location":"Montanha dos Sete Vales","bosses":["Yaksha dos Olhos Noturnos"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"09:30","location":"Montanha dos Sete Vales","bosses":["Yaksha dos Olhos Noturnos"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"15:30","location":"Montanha dos Sete Vales","bosses":["Yaksha dos Olhos Noturnos"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"21:30","location":"Montanha dos Sete Vales","bosses":["Yaksha dos Olhos Noturnos"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"03:30","location":"Montanha dos Sete Vales","bosses":["Tatu Gigante de Carapaça Sombria"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"06:30","location":"Montanha dos Sete Vales","bosses":["Tatu Gigante de Carapaça Sombria"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"09:30","location":"Montanha dos Sete Vales","bosses":["Tatu Gigante de Carapaça Sombria"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"12:30","location":"Montanha dos Sete Vales","bosses":["Tatu Gigante de Carapaça Sombria"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"15:30","location":"Montanha dos Sete Vales","bosses":["Tatu Gigante de Carapaça Sombria"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"18:30","location":"Montanha dos Sete Vales","bosses":["Tatu Gigante de Carapaça Sombria"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"21:30","location":"Montanha dos Sete Vales","bosses":["Tatu Gigante de Carapaça Sombria"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"00:30","location":"Montanha dos Sete Vales","bosses":["Tatu Gigante de Carapaça Sombria"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"04:30","location":"Ilha do Fogo Ardente","bosses":["Bulhu"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"10:30","location":"Ilha do Fogo Ardente","bosses":["Bulhu"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"16:30","location":"Ilha do Fogo Ardente","bosses":["Bulhu"],"tier":1},
  {"W":1,"layer":"Bicheon","time":"22:30","location":"Ilha do Fogo Ardente","bosses":["Bulhu"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"05:30","location":"Campo de Gelo do Dragão Noveno","bosses":["Gwe Mukang"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"11:30","location":"Campo de Gelo do Dragão Noveno","bosses":["Gwe Mukang"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"17:30","location":"Campo de Gelo do Dragão Noveno","bosses":["Gwe Mukang"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"23:30","location":"Campo de Gelo do Dragão Noveno","bosses":["Gwe Mukang"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"06:30","location":"Prisão Subterrânia","bosses":["Do Maengryong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"12:30","location":"Prisão Subterrânia","bosses":["Do Maengryong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"18:30","location":"Prisão Subterrânia","bosses":["Do Maengryong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"00:30","location":"Prisão Subterrânia","bosses":["Do Maengryong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"01:30","location":"Prisão Subterrânia","bosses":["Molgrash"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"04:30","location":"Prisão Subterrânia","bosses":["Molgrash"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"07:30","location":"Prisão Subterrânia","bosses":["Molgrash"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"10:30","location":"Prisão Subterrânia","bosses":["Molgrash"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"13:30","location":"Prisão Subterrânia","bosses":["Molgrash"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"16:30","location":"Prisão Subterrânia","bosses":["Molgrash"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"19:30","location":"Prisão Subterrânia","bosses":["Molgrash"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"22:30","location":"Prisão Subterrânia","bosses":["Molgrash"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"02:30","location":"Palacio do Dragão Noveno","bosses":["Wi Kwangryeong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"05:30","location":"Palacio do Dragão Noveno","bosses":["Wi Kwangryeong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"08:30","location":"Palacio do Dragão Noveno","bosses":["Wi Kwangryeong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"11:30","location":"Palacio do Dragão Noveno","bosses":["Wi Kwangryeong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"14:30","location":"Palacio do Dragão Noveno","bosses":["Wi Kwangryeong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"17:30","location":"Palacio do Dragão Noveno","bosses":["Wi Kwangryeong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"20:30","location":"Palacio do Dragão Noveno","bosses":["Wi Kwangryeong"],"tier":1},
  {"W":2,"layer":"Vale da Serpente","time":"23:30","location":"Palacio do Dragão Noveno","bosses":["Wi Kwangryeong"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"01:30","location":"Ruinas do Nerfariox Primal","bosses":["Krog"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"07:30","location":"Ruinas do Nerfariox Primal","bosses":["Krog"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"13:30","location":"Ruinas do Nerfariox Primal","bosses":["Krog"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"19:30","location":"Ruinas do Nerfariox Primal","bosses":["Krog"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"02:30","location":"Desfiladeiro Congelado","bosses":["Kelis"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"08:30","location":"Desfiladeiro Congelado","bosses":["Kelis"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"14:30","location":"Desfiladeiro Congelado","bosses":["Kelis"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"20:30","location":"Desfiladeiro Congelado","bosses":["Kelis"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"02:30","location":"Desfiladeiro Congelado","bosses":["Talasa"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"05:30","location":"Desfiladeiro Congelado","bosses":["Talasa"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"08:30","location":"Desfiladeiro Congelado","bosses":["Talasa"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"11:30","location":"Desfiladeiro Congelado","bosses":["Talasa"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"14:30","location":"Desfiladeiro Congelado","bosses":["Talasa"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"17:30","location":"Desfiladeiro Congelado","bosses":["Talasa"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"20:30","location":"Desfiladeiro Congelado","bosses":["Talasa"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"23:30","location":"Desfiladeiro Congelado","bosses":["Talasa"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"03:30","location":"Antiga Fortaleza dos Ancestrais","bosses":["Barkas"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"09:30","location":"Antiga Fortaleza dos Ancestrais","bosses":["Barkas"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"15:30","location":"Antiga Fortaleza dos Ancestrais","bosses":["Barkas"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"21:30","location":"Antiga Fortaleza dos Ancestrais","bosses":["Barkas"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"04:30","location":"Templo das Hidras","bosses":["Bargan"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"10:30","location":"Templo das Hidras","bosses":["Bargan"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"16:30","location":"Templo das Hidras","bosses":["Bargan"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"22:30","location":"Templo das Hidras","bosses":["Bargan"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"03:30","location":"Templo das Hidras","bosses":["Morg"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"06:30","location":"Templo das Hidras","bosses":["Morg"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"09:30","location":"Templo das Hidras","bosses":["Morg"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"12:30","location":"Templo das Hidras","bosses":["Morg"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"15:30","location":"Templo das Hidras","bosses":["Morg"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"18:30","location":"Templo das Hidras","bosses":["Morg"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"21:30","location":"Templo das Hidras","bosses":["Morg"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"00:30","location":"Templo das Hidras","bosses":["Morg"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"05:30","location":"Abisso de Hidra","bosses":["Bordo"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"11:30","location":"Abisso de Hidra","bosses":["Bordo"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"17:30","location":"Abisso de Hidra","bosses":["Bordo"],"tier":1},
  {"W":3,"layer":"Centro Espiritual","time":"23:30","location":"Abisso de Hidra","bosses":["Bordo"],"tier":1}
];

// 2. DADOS DE CRAFTING
export const CRAFTING_RECIPES_DATA: CraftingData = {
  "Pó Brilhante": {
      // Fix: The type for 'category' is string, but a boolean was provided. Corrected to a string value.
      "category": "Materiais Raros",
      "materials": [
          { "name": "Erva Brilhante", "quantity": 10 }
      ]
  },
  "Peça de Equipamento Épico": {
      "category": "Equipamentos",
      "materials": [
          { "name": "Aço de Dragão Épico", "quantity": 100 },
          { "name": "Couro de Dragão Épico", "quantity": 50 },
          { "name": "Escama de Dragão Épica", "quantity": 25 },
          { "name": "Chifre de Dragão Épico", "quantity": 10 }
      ]
  },
  "Pílula de Vigor (M)": {
      "category": "Consumíveis",
      "materials": [
          { "name": "Pílula de Vigor (P)", "quantity": 10 },
          { "name": "Pó Brilhante", "quantity": 1 }
      ]
  }
};
